spring:
  application:
    name: cron-videos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cron_videos
    username: root
    password: 12345678
  data:
    redis:
      host: 127.0.0.1
      password: 12345678
      database: 0
      port: 6379
  task:
    scheduling:
      pool:
        size: 5
logging:
  level:
    com.roukaixin.cronvideos.mapper: debug
    com.roukaixin.cronvideos.service: debug
    com.roukaixin.cronvideos.listener: debug
    com.roukaixin.cronvideos.downloader: debug

  file:
    path: ./log
  logback:
    rollingpolicy:
      max-history: 2
server:
  port: 9080
mybatis:
  type-handlers-package: com.roukaixin.cronvideos.handler.mybatis
  type-aliases-package: com.roukaixin.cronvideos.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: "classpath:mapper/**"